### ISSUE TITLE
Default Settings channel code BHZ results in invalid channel codes when using 'Add a default Network'

### ISSUE THREAD

**Issue by gillian-earthscope** [iris-edu/yasmine-stationxml-editor#16]
The default channel code in Settings is BHZ, but this leads to issues with 'Add a default Network'.  When you add a default network, it automatically creates channels BHZ0, BHZ1, BHZ2, etc. which are not valid channels (channels must be 3-characters).

If you change the channel code in Settings to BH, then it automatically creates valid channels BH0, BH1, BH2, etc. (using 'add a default network). However if you then select a station and choose 'add a default channel' it then creates channel 'BH' which is not a valid channel.

**Comment by rcasey-earthscope** [comment]
Looks like this feature was implemented in the nrlv2 branch and possibly main.
