### ISSUE TITLE
starting YASMINE for the first time using docker, fails because it can't find data directory

### ISSUE THREAD

**Issue by gillian-earthscope** [iris-edu/yasmine-stationxml-editor#18]
One issue I ran into with running Yasmine for the first time is that there is no data directory and it stops with an error. I can get past this by manually creating a data directory. 

% pwd
/Users/gilliansharer/yasmine-stationxml-editor
% docker compose up
[+] Running 3/4
 ⠿ Network "yasmine-stationxml-editor_yasmine" Created                                           4.8s
 ⠿ Network "yasmine-stationxml-editor_default" Created                                           4.1s
 ⠹ Container yasmine-backend          Creating                                          0.2s
 ⠿ Container yasmine-frontend          Created                                           0.2s
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /Users/gilliansharer/yasmine-stationxml-editor/data
% mkdir data
% docker compose up
[+] Running 1/1
 ⠿ Container yasmine-backend Created                                                                                       0.1s
Attaching to yasmine-backend, yasmine-frontend
yasmine-frontend | Sencha Cmd v6.5.3.6
yasmine-backend  | INFO [alembic.runtime.migration] Context impl SQLiteImpl.
yasmine-backend  | INFO [alembic.runtime.migration] Will assume non-transactional DDL.
etc., now it works

**Comment by rcasey-earthscope** [comment]
Let's review and see if this is still an issue.
