### ISSUE TITLE
Installation fails with numpy 1.22.2

### ISSUE THREAD

**Issue by jmsaurel** [iris-edu/yasmine-stationxml-editor#3]
Yasmine base migration (`syncdb upgrade heads`) fails when using numpy version 1.22.2.

The error is in **alembic**, when performing `run_migrations`.

`AttributeError: 'numpy.int64' object has no attribute 'split'`

Downgrading to numpy 1.21.5, it works.
This was observed on Linux and Windows.

**Comment by pevans-gfz** [comment]
ObsPy 1.3 [says](https://newreleases.io/project/pypi/obspy/release/1.3.0) it requires Python 3.7. To build with Docker Compose, I (i) changed `requirements.txt`, (ii) updated the base image used in `backend/Dockerfile`:

```
FROM python:3.7-slim
```

**Comment by jmsaurel** [comment]
Hello @pevans-gfz , thanks for proposing a fix to this one.

Could you push a pull-request with your suggested changes ?
